remote_theme: mmistakes/jekyll-theme-basically-basic
lang: en-US
title: "The Monday Knights"
description: "Play updates and resources for The Monday Knights"
url: http://claydowling.github.io/mondayknights
author: Clay Dowling
twitter_username: ClayDowling
github_username: ClayDowling
search: true

gems:
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/