remote_theme: "mmistakes/minimal-mistakes"

locale: "en-US"
title: "Monday Knights"
title_separator: "-"
description: "Steampunk Adventures"
name: &name "Clay Dowling"
base-url: "/mondayknights/"

author:
        name: *name
        bio: "Game master, RPG fan. Supplier of whiskey to golden coated cats."
        avatar: "/assets/images/clay-with-kronos.jpg"
        location: "Dexter, MI"
        email: "clay@lazarusid.com"
        uri: "http://claydowling.com"

search: true
search_full_content: true
minimal_mistakes_skin: contrast

include:
  - _pages
  - assets

collections:
  adventures:
    output: true
    permalink: /:collection/:name:output_ext
  world:
    output: true
    permalink: /:collection/:name:output_ext

defaults:
        # _posts
        - scope:
                path: ""
                type: posts
          values:
                  layout: single
                  author_profile: true
                  read_time: true
                  share: true
                  related: true
        # _pages
        - scope:
                path: ""
                type: pages
          values:
                layout: single
                author_profile: true
        # _adventures
        - scope:
                path: ""
                type: adventures
          values:
                layout: single
                author_profile: 
                related: true
        # _world
        - scope:
                path: ""
                type: world
          values:
                layout: single
                author_profile: false
                related: true
